#pragma once

enum CAN_MessageID {
    REQ_OCCUPANCY = 1,
    TX_OCCUPANCY = 2,
    BR_ENTRY_NOTICE = 3,
    TX_ENTRY_REGISTRATION = 4,
    TX_SPOT_INFO = 5,
    BR_STATE = 6,
    TX_VALIDATION = 7,
    TX_VALIDATED_REG = 8,
    BR_EXIT = 9,
    REQ_SESSION_DATA = 10,
    TX_SESSION_DATA = 11,
    CMD_GATE_CONTROL = 12
};
