[platformio]
src_dir = nodes
extra_configs = nodes/*/node_config.ini

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = https://github.com/autowp/arduino-mcp2515.git
build_flags = 
    -I lib/common 
    -std=gnu++2a
build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17

