[platformio]
default_envs = node_ui
src_dir = nodes

[env:node_ui]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = -<*> +<node_ui/src/>
build_flags = 
    -I nodes/node_ui/include 
    -I lib/common
lib_deps = https://github.com/autowp/arduino-mcp2515.git

[env:node_firesys]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = -<*> +<node_firesys/src/>
build_flags = 
    -I nodes/node_firesys/include 
    -I lib/common
lib_deps = https://github.com/autowp/arduino-mcp2515.git


